#include "StandardGenerator.h"

#include "../Node/Node.h"

namespace CHTL
{
    std::string StandardGenerator::generate(const Node& root)
    {
        (void)root;
        return "<!-- generated by CHTL StandardGenerator -->\n";
    }
}